feat: Combine action status

diff --git a/.github/workflows/validate-phar.yml b/.github/workflows/validate-phar.yml
--- a/.github/workflows/validate-phar.yml
+++ b/.github/workflows/validate-phar.yml
@@ -6,7 +6,7 @@ on:
     branches:
       - "[0-9]+.[0-9]+.x"
       - main
-    pull_request:
+  pull_request:
 
 env:
   COMPOSER_VERSION: "^2.1"
@@ -74,3 +74,27 @@ jobs:
 
       - name: "Validate composer-unused.phar against code"
         run: "php ${{ env.COMPOSER_UNUSED_PHAR }} --excludeDir=data"
+
+  aggregate-validate-phar:
+    name: Phar Requirement Check
+    runs-on: ubuntu-latest
+    needs: [ phar ]
+    if: always()
+    steps:
+      - name: Check Overall Status
+        run: |
+          failed=0
+          for job in $(jq -r 'keys_unsorted[]' <<< '${{ toJson(needs) }}'); do
+            result=$(jq -r --arg job "$job" '.[$job].result' <<< '${{ toJson(needs) }}')
+            echo "Job: $job - Status: $result"
+            if [[ "$result" != "success" ]]; then
+              failed=1
+            fi
+          done
+          if [[ "$failed" -eq 0 ]]; then
+            echo "✅ All jobs succeeded"
+            exit 0
+          else
+            echo "❌ Some jobs failed"
+            exit 1
+          fi
